"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const dbg = require("debug");
const h = require("./helpers/misc.js");
const sql = require("mssql");
const config = require("../config/sql.js");
const categoriesRouter = require("./routers/categoriesRouter.js");
const bodyParser = require("body-parser");
// import tempTests = require('./tempTesting');
const debug = dbg('todo:api');
class main {
    run() {
        debug.enabled = true;
        let monField = new h.Helpers.SqlField({ type: "nvarchar(100)", name: "momo" });
        debug(monField.name);
        process.on('unhandledRejection', (err) => {
            debug('unhandledRejection ', err);
        });
        const app = express();
        app.use(bodyParser.urlencoded({ extended: true }));
        app.use(bodyParser.json());
        app.get(['/get', '/'], (req, res) => {
            res.send('Todo service apis.');
        });
        const pool = new sql.ConnectionPool(config, (err) => {
            if (err) {
                debug("error in getting the connection pool");
                throw (err);
            }
            const categoriesFields = [
                new h.Helpers.SqlField({ name: 'id', type: 'bigint' }),
                new h.Helpers.SqlField({ name: 'title', type: 'nvarchar(100)' }),
                new h.Helpers.SqlField({ name: 'sortId', type: 'int' }),
                new h.Helpers.SqlField({ name: 'modifiedOn', type: 'datetime' }),
            ];
            const categoriesTable = new h.Helpers.SqlTableType({ connectionPool: pool, tableName: 'categories', fields: categoriesFields, autoGeneratedPrimaryKey: false });
            debug(categoriesTable.getFieldNames(true));
            const cr = new categoriesRouter.CategoriesRouter(categoriesTable, false);
            app.use('/categories', cr.router);
        });
        const port = process.env.PORT || 3000;
        app.listen(port, function () {
            debug(`listening on port ${port}`);
        });
    }
}
let m = new main();
m.run();
//# sourceMappingURL=app.js.map