"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const dbg = require("debug");
const h = require("./helpers/misc.js");
const sql = require("mssql");
const config = require("../config/sql.js");
const categoriesRouter = require("./routers/categoriesRouter.js");
const bodyParser = require("body-parser");
const baseRouter = require("./routers/baseRouter.js");
const odataV4Sql = require("odata-v4-sql");
const debug = dbg('todo:api');
class main {
    run() {
        debug.enabled = true;
        let reqUrl = `/?$filter=(Name%20eq%20%27John%27%20and%20LastName%20lt%20%27Doe%27)%20or%20(adress%20eq%20%27Skondalsvag%201%27%20and%20postnummer%20gt%2012868%20and%20postort%20eq%20%27Skondal%27)`;
        reqUrl = '$top=100';
        reqUrl = reqUrl.substring(reqUrl.indexOf('$'), reqUrl.length);
        debug(reqUrl);
        const filter = odataV4Sql.createQuery(reqUrl);
        debug(filter.where);
        process.on('unhandledRejection', (err) => {
            debug('unhandledRejection ', err);
        });
        const app = express();
        app.use(bodyParser.urlencoded({ extended: true }));
        app.use(bodyParser.json());
        app.get(['/get', '/'], (req, res) => {
            res.send('Todo service apis.');
        });
        const pool = new sql.ConnectionPool(config, (err) => {
            if (err) {
                debug("error in getting the connection pool");
                throw (err);
            }
            const categoriesFields = [
                new h.Helpers.SqlField({ name: 'id', type: sql.BigInt }),
                new h.Helpers.SqlField({ name: 'title', type: sql.NVarChar(50) }),
                new h.Helpers.SqlField({ name: 'sortId', type: sql.Int }),
                new h.Helpers.SqlField({ name: 'modifiedOn', type: sql.DateTime }),
            ];
            const categoriesTable = new h.Helpers.SqlTableType({ connectionPool: pool, tableName: 'categories', fields: categoriesFields, autoGeneratedPrimaryKey: true });
            const cr = new categoriesRouter.CategoriesRouter(categoriesTable, false);
            app.use('/categories', cr.router);
            const tagsFields = [
                new h.Helpers.SqlField({ name: 'id', type: sql.BigInt }),
                new h.Helpers.SqlField({ name: 'title', type: sql.NVarChar(50) }),
                new h.Helpers.SqlField({ name: 'sortId', type: sql.Int }),
                new h.Helpers.SqlField({ name: 'modifiedOn', type: sql.DateTime }),
            ];
            const tagsTable = new h.Helpers.SqlTableType({ connectionPool: pool, tableName: 'tags', fields: tagsFields, autoGeneratedPrimaryKey: true });
            const tagsRouter = new baseRouter.BaseRouter(tagsTable, false);
            app.use('/tags', tagsRouter.router);
        });
        const port = process.env.PORT || 3000;
        app.listen(port, function () {
            debug(`listening on port ${port}`);
        });
    }
}
let m = new main();
m.run();
//# sourceMappingURL=app.js.map