"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sql = require("mssql");
const dbg = require("debug");
const misc_1 = require("../helpers/misc");
const sqlTableType_1 = require("./sqlTableType");
const debug = dbg('todo:activityCardsTable');
class ActivityCardsTable extends sqlTableType_1.SqlTableType {
    constructor(connectionPool) {
        const activityCardsFields = [
            new misc_1.Helpers.SqlField({ name: 'id', type: sql.BigInt }),
            new misc_1.Helpers.SqlField({ name: 'activityId', type: sql.BigInt }),
            new misc_1.Helpers.SqlField({ name: 'notes', type: sql.NVarChar(sql.MAX) }),
            new misc_1.Helpers.SqlField({ name: 'cardType', type: sql.NVarChar(50) }),
            new misc_1.Helpers.SqlField({ name: 'input', type: sql.NVarChar(sql.MAX) }),
            new misc_1.Helpers.SqlField({ name: 'outputText', type: sql.NVarChar(sql.MAX) }),
            new misc_1.Helpers.SqlField({ name: 'modifiedOn', type: sql.DateTime }),
        ];
        super({ connectionPool: connectionPool, tableName: 'ActivityCardsBase', viewName: 'ActivityCardsBase', fields: activityCardsFields, autoGeneratedPrimaryKey: true, throwOnExtraFields: true });
        debug.enabled = true;
    }
}
exports.ActivityCardsTable = ActivityCardsTable;
//# sourceMappingURL=activityCardsTable.js.map