"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sql = require("mssql");
const dbg = require("debug");
const h = require("../helpers/misc");
const sqlTableType_1 = require("./sqlTableType");
const debug = dbg('todo:todoCardsTable');
class TodoCardsTable extends sqlTableType_1.SqlTableType {
    constructor(connectionPool) {
        const todoCardsFields = [
            new h.Helpers.SqlField({ name: 'id', type: sql.BigInt }),
            new h.Helpers.SqlField({ name: 'todoId', type: sql.BigInt }),
            new h.Helpers.SqlField({ name: 'notes', type: sql.NVarChar(sql.MAX) }),
            new h.Helpers.SqlField({ name: 'cardType', type: sql.NVarChar(50) }),
            new h.Helpers.SqlField({ name: 'input', type: sql.NVarChar(sql.MAX) }),
            new h.Helpers.SqlField({ name: 'outputText', type: sql.NVarChar(sql.MAX) }),
            new h.Helpers.SqlField({ name: 'outputMedia', type: sql.VarBinary(sql.MAX) }),
            new h.Helpers.SqlField({ name: 'modifiedOn', type: sql.DateTime }),
        ];
        super({ connectionPool: connectionPool, tableName: 'TodoCardsBase', viewName: 'TodoCardsBase', fields: todoCardsFields, autoGeneratedPrimaryKey: true, throwOnExtraFields: true });
        debug.enabled = true;
    }
    async customUpdateChecks(jsonBody) {
        return;
    }
    async customInsertChecks(jsonBody) {
        return;
    }
}
exports.TodoCardsTable = TodoCardsTable;
//# sourceMappingURL=todoCardsTable.js.map