import sql = require('mssql');
import dbg = require('debug');
import h = require('../helpers/misc');
import odataV4Sql = require('odata-v4-sql');
import { SqlTableType } from './sqlTableType';

const debug = dbg('todo:todoCardsTable');

export class TodoCardsTable extends SqlTableType {
  constructor(connectionPool: sql.ConnectionPool) {
    const todoCardsFields: h.Helpers.SqlField[] = [
      new h.Helpers.SqlField({ name: 'id', type: sql.BigInt }),
      new h.Helpers.SqlField({ name: 'todoId', type: sql.BigInt }),
      new h.Helpers.SqlField({ name: 'notes', type: sql.NVarChar(sql.MAX) }),
      new h.Helpers.SqlField({ name: 'cardType', type: sql.NVarChar(50) }),
      new h.Helpers.SqlField({ name: 'input', type: sql.NVarChar(sql.MAX) }),
      new h.Helpers.SqlField({ name: 'outputText', type: sql.NVarChar(sql.MAX) }),
      new h.Helpers.SqlField({ name: 'outputMedia', type: sql.VarBinary(sql.MAX) }),
      new h.Helpers.SqlField({ name: 'modifiedOn', type: sql.DateTime }),
    ];

    super({ connectionPool: connectionPool, tableName: 'TodoCardsBase', viewName: 'TodoCardsBase', fields: todoCardsFields, autoGeneratedPrimaryKey: true, throwOnExtraFields: true });
    debug.enabled = true;
  }

  async customUpdateChecks(jsonBody: any) {
    return;
  }
  async customInsertChecks(jsonBody: any) {
    return;
  }
}